name: alphatracker-test2
dependencies:
  - python=3.7
  - jupyter
  - h5py
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - pyqt
  - tqdm
  - seaborn
  - scipy
  - pip:
    - imageio==2.9.0
    - imgaug==0.4.0
    - munkres==1.1.4
    - natsort==7.1.1
    - networkx==2.5
    - nibabel==3.2.1
    - opencv-python==4.5.1.48
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - scikit-image==0.18.1
    - shapely==1.7.1
    - tensorboard==2.4.1
    - tensorboardX
    - "git+https://github.com/ZexinChen/torchsample"
    

